# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1caf4e46c10f61e04e1e5bb59ffdb51bc62436173f06ed0669fe5d6af8bf4d18d3bd8911c2a9d8c568b2a77a1361dfe14d083fd48ed5a07f3ad46a297eefffae

test:
  secret_key_base: 44306466f331298e9b567aa43d6f13233508322f4088bc769bd773fe2a54db3c70b74ac44db7a4c5dea164142fbb24a01cc1f22aa54522bff520f1849c22b5bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
